# Generated by Django 4.1 on 2023-11-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_time', models.DateTimeField()),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreInfo',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.CharField(max_length=50)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='mylogin.examinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='mylogin.userinfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_scores', to='mylogin.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='mylogin.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CheckScoreInfo',
            fields=[
                ('check_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_successful', models.BooleanField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_checks', to='mylogin.examinfo')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_checks', to='mylogin.scoreinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_checks', to='mylogin.userinfo')),
            ],
        ),
    ]
